apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: electrumx
    name: electrumx
    namespace: electrumx
  spec:
    ports:
    - name: electrum
      port: 50001
      protocol: TCP
      targetPort: 50001
    - name: electrum-ssl
      port: 50002
      protocol: TCP
      targetPort: 50002
    selector:
      run: electrumx
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: monacoind
    name: monacoind
    namespace: electrumx
  spec:
    ports:
    - port: 9402
      protocol: TCP
      targetPort: 9402
    selector:
      run: monacoind
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
